### ISSUE TITLE
CD Pipeline

### ISSUE THREAD

**Issue by iphilpot** [microsoft/orion#10]
### Description
As an Engineer, I want the software released on GitHub when merged to Master Branch, so that users can download.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should use AzDO release pipeline
- [ ] Should Contain metadata for release
- [ ] Should contain semver tag
- [ ] Should contain linux/mac binaries

Also, here are a few points that need to be addressed:

1. WSL should support Linux binary

### Resources
na

### Tasks
- [ ] Research AzDO common practices for creating GitHub releases
- [ ] ianphil and clewolff both have scripts that can do this. Review both.
- [ ] Create release pipeline in AzDO
