### ISSUE TITLE
Add "New Bug Report" template to repo

### ISSUE THREAD

**Issue by iphilpot** [microsoft/orion#12]
### Description
As a user, I want a well-defined method for filing bugs, so that I give/collect all the information needed.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should explain the issue
- [ ] Should ask for repo steps

### Resources
[Ansible bug report example](https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE/bug_report.md)

### Tasks
- [ ] Place file in repo and commit/push/pr
