### ISSUE TITLE
User Sequence Diagram

### ISSUE THREAD

**Issue by iphilpot** [microsoft/orion#13]
### Description
As a developer, I want a sequence diagram that details the use of the CLI, so I can understand how and what the CLI does.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should contain all planned cmds
- [ ] Should detail what happens when a cmd is executed

### Resources
na

### Tasks
- [ ] Create VISIO diagram
- [ ] Setup cmd
- [ ] Test cmd
- [ ] New cmd
- [ ] New Sub-cmds
