### ISSUE TITLE
CI/CD Pipeline workflow/design

### ISSUE THREAD

**Issue by nmiodice** [microsoft/orion#23]
### Description
*As a orion developer I'd like to validate my changes and publish new builds via CI/CD pipelines. These should be designed to ensure that the use cases are flexible and enable testing in a cloud-agnostic manner*

### Acceptance Criteria
- [ ] Gather use-cases for CI/CD pipeline
- [ ] Write design for CI/CD pipeline
- [ ] Gather PR feedback from [TBD] stakeholders
- [ ] Diagrams for CI/CD workflow

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
