### ISSUE TITLE
Handle Ctrl-C (cancelation) 

### ISSUE THREAD

**Issue by iphilpot** [microsoft/orion#24]
**A good user story should be (I-N-V-E-S-T principle)**

* _Independent_ (from other user stories, allowing to realize them in any order);
* _Negotiable_ (omit details that would freeze the story);
* _Valuable_ (implementation delivers an increment of functionality, observable by and useful to users);
* _Estimable_ (developers should be able to estimate its size relative to other stories);
* _Sizable_ (implementation fits in one iteration – if it needs many to complete, it is an EPIC);
* _Testable_ (user must be able to check the conditions of satisfaction).

### Description
As a user, I want the ability to cancel the CLI, and ensure things are cleaned up.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should provide a well-formated message to the user
- [ ] Should capture "signal c"
- [ ] Should remove work from temporary workspace

Also, here are a few points that need to be addressed:

1. I want to be careful and not have us create a transactional system here with roll-back etc. Show what work we've done and clean up temporary workspace.

### Resources
```go
c := make(chan os.Signal, 1)
signal.Notify(c, os.Interrupt)
go func(){
    for sig := range c {
        // sig is a ^C, handle it
    }
}()
```

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
