### ISSUE TITLE
Setup cmd should scaffold infra folder structure

### ISSUE THREAD

**Issue by iphilpot** [microsoft/orion#7]
### Description
As a user, I want the entire infra folder, so that I can pin to a specific version.

### Acceptance Criteria
- [ ] Should contain infra folder
- [ ] Should contain all modules
- [ ] Should contain only specified template folder/files

Also, here are a few points that need to be addressed:

1. The current implementation only downloads files to pwd.

### Resources
Modify the current mv func to address Acceptance criteria.
[Code](https://github.com/microsoft/orion/blob/5f78e5ef8b590ebeafab08c5ff031d7173f0f557/cli/scaffolding/scaffold.go#L45)

### Tasks

 - [] Create infra in pwd
 - [] mv modules folder to pwd/infra
 - [] Create infra/templates folder
 - [] mv specified template folder and files to pwd/infra/templates folder
