### ISSUE TITLE
CI Pipeline

### ISSUE THREAD

**Issue by iphilpot** [microsoft/orion#9]
### Description
As an Engineer, I want a CI pipeline that will build and test the code, so I can ensure it's correct.

### Acceptance Criteria
- [ ] Should build for Linux
- [ ] Should build for Mac
- [ ] Should past all unit tests

Also, here are a few points that need to be addressed:

1. There are no current integration testing needs

### Resources
na

### Tasks
 - [ ] Create an AzDO pipeline using Cobalt infrastrcuture
 - [ ] Use make build with env vars for Linux
 - [ ] Use make build with env vars for Mac
 - [ ] Use make test and ensure all tests pass
